# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{serialport}
  s.version = "1.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Guillaume Pierronnet", "Alan Stern", "Daniel E. Shipton", "Tobin Richard", "Hector Parra", "Ryan C. Payne", "jens alexander ewald"]
  s.date = %q{2011-03-05}
  s.description = %q{Ruby/SerialPort is a Ruby library that provides a class for using RS-232 serial ports.}
  s.email = %q{jens@ififelse.net}
  s.extensions = ["ext/native/extconf.rb", "ext/native/extconf.rb"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "MANIFEST",
    "README",
    "Rakefile",
    "VERSION",
    "ext/native/extconf.rb",
    "ext/native/posix_serialport_impl.c",
    "ext/native/serialport.c",
    "ext/native/serialport.h",
    "ext/native/win_serialport_impl.c",
    "lib/serialport.rb",
    "serialport.gemspec",
    "test/miniterm.rb",
    "test/set_readtimeout.rb"
  ]
  s.homepage = %q{http://github.com/jens-a-e/ruby-serialport/}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.3}
  s.summary = %q{Library for using RS-232 serial ports.}
  s.test_files = [
    "test/miniterm.rb",
    "test/set_readtimeout.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

